import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/OnDemand.module.css';

export default function Home() {
  return (
    <div className='bg-neutral-50 px-8'>
      <Head>
        <title>Livepeer Studio App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href='https://livepeerjs.org/docs/getting-started.en-US'>
            Welcome to Livestream SDK 📹
          </Link>
        </h1>

        <div className={styles.grid}>
          <Link href='livestreamSDK/useCreateStream'>
            <a className={styles.card}>
              <h2>UseCreateStream &rarr;</h2>
              <p>Creates a stream for livestreaming</p>
            </a>
          </Link>

          <Link href='livestreamSDK/useStream'>
            <a className={styles.card}>
              <h2>UseStream &rarr;</h2>
              <p>Gets a livestream based on the stream ID</p>
            </a>
          </Link>

          {/* <Link href='livestreamSDK/useStreamSession'>
            <a className={styles.card}>
              <h2>UseStreamSession&rarr;</h2>
              <p>Get a session by ID</p>
            </a>
          </Link> */}

          <Link href='livestreamSDK/useStreamSessions'>
            <a className={styles.card}>
              <h2>UseStreamSessions&rarr;</h2>
              <p>Get all sessions</p>
            </a>
          </Link>

          <Link href='livestreamSDK/useUpdateStream'>
            <a className={styles.card}>
              <h2>Update Stream&rarr;</h2>
              <p>Enable recording, multistream, and suspending of a stream</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
